import jsPDF from "jspdf";

function safeText(value, fallback = "-") {
  if (value === null || value === undefined || value === "") return fallback;
  return String(value);
}

function money(value) {
  const number = Number(value || 0);
  return number.toLocaleString("en-PK");
}

function roomArea(room, scale) {
  const widthFt = Math.round((room.width || 0) / scale);
  const heightFt = Math.round((room.height || 0) / scale);
  return {
    widthFt,
    heightFt,
    area: Math.max(1, widthFt * heightFt)
  };
}

function addHeader(doc, plan, pageTitle) {
  doc.setFillColor(8, 16, 34);
  doc.rect(0, 0, 210, 22, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("NexaCAD AI Pro", 14, 14);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(pageTitle, 150, 14);

  doc.setTextColor(30, 41, 59);
  doc.setFontSize(9);
  doc.text(safeText(plan.title, "Architecture Project"), 14, 29);
}

function addFooter(doc, pageNumber) {
  doc.setDrawColor(226, 232, 240);
  doc.line(14, 282, 196, 282);

  doc.setTextColor(100, 116, 139);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("Generated by NexaCAD AI Pro - Concept proposal for client review", 14, 288);
  doc.text(`Page ${pageNumber}`, 184, 288);
}

function addSectionTitle(doc, title, y) {
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(title, 14, y);

  doc.setDrawColor(37, 99, 235);
  doc.setLineWidth(0.6);
  doc.line(14, y + 3, 196, y + 3);
}

function addKeyValue(doc, label, value, x, y) {
  doc.setFont("helvetica", "bold");
  doc.setTextColor(71, 85, 105);
  doc.setFontSize(9);
  doc.text(label, x, y);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.text(safeText(value), x, y + 6);
}

function addTableHeader(doc, headers, widths, x, y) {
  doc.setFillColor(15, 23, 42);
  doc.rect(x, y, widths.reduce((a, b) => a + b, 0), 8, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);

  let currentX = x + 2;
  headers.forEach((header, index) => {
    doc.text(header, currentX, y + 5.4);
    currentX += widths[index];
  });
}

function addTableRow(doc, values, widths, x, y, fill = false) {
  if (fill) {
    doc.setFillColor(248, 250, 252);
    doc.rect(x, y, widths.reduce((a, b) => a + b, 0), 8, "F");
  }

  doc.setDrawColor(226, 232, 240);
  doc.rect(x, y, widths.reduce((a, b) => a + b, 0), 8);

  doc.setTextColor(30, 41, 59);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);

  let currentX = x + 2;
  values.forEach((value, index) => {
    const text = safeText(value);
    doc.text(text.length > 28 ? `${text.slice(0, 25)}...` : text, currentX, y + 5.3);
    currentX += widths[index];
  });
}

function calculateSummary(plan) {
  const scale = plan.scale || 12;
  const rooms = Array.isArray(plan.rooms) ? plan.rooms : [];
  const furniture = Array.isArray(plan.furniture) ? plan.furniture : [];
  const electrical = Array.isArray(plan.electrical) ? plan.electrical : [];
  const plumbing = Array.isArray(plan.plumbing) ? plan.plumbing : [];

  const totalArea = rooms.reduce((sum, room) => {
    return sum + roomArea(room, scale).area;
  }, 0);

  const coveredArea = totalArea || Number(plan.stats?.floorArea || 0) || 0;
  const greyStructureRate = 4200;
  const finishingRate = 3500;
  const estimatedCost = coveredArea * (greyStructureRate + finishingRate);

  return {
    rooms,
    furniture,
    electrical,
    plumbing,
    totalArea,
    coveredArea,
    greyStructureRate,
    finishingRate,
    estimatedCost
  };
}

export function downloadClientProposalPdf(plan) {
  if (!plan) {
    alert("Generate or open a project first.");
    return;
  }

  const doc = new jsPDF("p", "mm", "a4");
  const summary = calculateSummary(plan);
  const scale = plan.scale || 12;
  let page = 1;

  // Cover page
  doc.setFillColor(2, 6, 23);
  doc.rect(0, 0, 210, 297, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.text("NexaCAD AI Pro", 18, 45);

  doc.setFontSize(18);
  doc.text("Architecture Concept Proposal", 18, 62);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(191, 219, 254);
  doc.text("AI Floor Plan + CAD Editor + 3D Preview + Exterior Concept", 18, 74);

  doc.setFillColor(15, 23, 42);
  doc.roundedRect(18, 96, 174, 76, 6, 6, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(safeText(plan.title, "Architecture Project"), 28, 115);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(226, 232, 240);
  doc.text(`Plot: ${safeText(plan.plot?.width, 30)} x ${safeText(plan.plot?.length, 60)} ft`, 28, 130);
  doc.text(`Floors: ${safeText(plan.floors, 1)}`, 28, 141);
  doc.text(`Rooms: ${summary.rooms.length}`, 28, 152);
  doc.text(`Covered Area: ${summary.coveredArea} sq ft`, 28, 163);

  doc.setTextColor(148, 163, 184);
  doc.setFontSize(9);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 18, 268);
  doc.text("Prepared using NexaCAD AI Pro", 18, 278);

  // Page 2 summary
  doc.addPage();
  page += 1;
  addHeader(doc, plan, "Project Summary");
  addSectionTitle(doc, "Project Overview", 42);

  addKeyValue(doc, "Project Title", plan.title, 14, 55);
  addKeyValue(doc, "Plot Size", `${plan.plot?.width || 30} x ${plan.plot?.length || 60} ft`, 80, 55);
  addKeyValue(doc, "Floors", plan.floors || 1, 145, 55);

  addKeyValue(doc, "Total Rooms", summary.rooms.length, 14, 78);
  addKeyValue(doc, "Covered Area", `${summary.coveredArea} sq ft`, 80, 78);
  addKeyValue(doc, "Facade Style", plan.facade?.style || "Modern", 145, 78);

  addSectionTitle(doc, "Feature Summary", 110);

  const featureRows = [
    ["2D CAD Plan", "Included"],
    ["3D Floor Preview", "Included"],
    ["Exterior Elevation", "Included"],
    ["Furniture Layout", `${summary.furniture.length} objects`],
    ["Electrical Plan", `${summary.electrical.length} points`],
    ["Plumbing Plan", `${summary.plumbing.length} points`],
    ["BOQ / Estimate", "Concept estimate included"]
  ];

  let y = 122;
  addTableHeader(doc, ["Module", "Status"], [90, 70], 14, y);
  y += 8;
  featureRows.forEach((row, index) => {
    addTableRow(doc, row, [90, 70], 14, y, index % 2 === 0);
    y += 8;
  });

  addSectionTitle(doc, "Important Note", 205);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text(
    doc.splitTextToSize(
      "This proposal is an AI-generated concept package for early client discussion. Final construction drawings must be verified and approved by a licensed architect/engineer according to local building bylaws, structural requirements, MEP standards, and site conditions.",
      180
    ),
    14,
    218
  );

  addFooter(doc, page);

  // Page 3 room schedule
  doc.addPage();
  page += 1;
  addHeader(doc, plan, "Room Schedule");
  addSectionTitle(doc, "Room Dimensions and Area", 42);

  y = 54;
  addTableHeader(doc, ["Room", "Floor", "Dimensions", "Area"], [70, 25, 45, 35], 14, y);
  y += 8;

  summary.rooms.forEach((room, index) => {
    if (y > 260) {
      addFooter(doc, page);
      doc.addPage();
      page += 1;
      addHeader(doc, plan, "Room Schedule");
      y = 42;
      addTableHeader(doc, ["Room", "Floor", "Dimensions", "Area"], [70, 25, 45, 35], 14, y);
      y += 8;
    }

    const area = roomArea(room, scale);
    addTableRow(
      doc,
      [
        room.name || room.type || "Room",
        room.floor === 0 ? "Ground" : `Floor ${room.floor}`,
        `${area.widthFt} x ${area.heightFt} ft`,
        `${area.area} sq ft`
      ],
      [70, 25, 45, 35],
      14,
      y,
      index % 2 === 0
    );

    y += 8;
  });

  addFooter(doc, page);

  // Page 4 estimate
  doc.addPage();
  page += 1;
  addHeader(doc, plan, "BOQ / Cost Estimate");
  addSectionTitle(doc, "Concept Cost Estimate", 42);

  y = 56;
  addTableHeader(doc, ["Item", "Qty / Area", "Rate", "Amount"], [65, 35, 40, 45], 14, y);
  y += 8;

  const greyAmount = summary.coveredArea * summary.greyStructureRate;
  const finishingAmount = summary.coveredArea * summary.finishingRate;

  const estimateRows = [
    ["Grey Structure", `${summary.coveredArea} sq ft`, `PKR ${money(summary.greyStructureRate)}`, `PKR ${money(greyAmount)}`],
    ["Finishing Work", `${summary.coveredArea} sq ft`, `PKR ${money(summary.finishingRate)}`, `PKR ${money(finishingAmount)}`],
    ["Furniture Objects", `${summary.furniture.length}`, "Concept", "As selected"],
    ["Electrical Points", `${summary.electrical.length}`, "Concept", "As per market"],
    ["Plumbing Points", `${summary.plumbing.length}`, "Concept", "As per market"]
  ];

  estimateRows.forEach((row, index) => {
    addTableRow(doc, row, [65, 35, 40, 45], 14, y, index % 2 === 0);
    y += 8;
  });

  doc.setFillColor(37, 99, 235);
  doc.roundedRect(14, y + 10, 182, 18, 4, 4, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(`Estimated Concept Total: PKR ${money(summary.estimatedCost)}`, 22, y + 22);

  addSectionTitle(doc, "Disclaimer", y + 50);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  doc.setFontSize(9);
  doc.text(
    doc.splitTextToSize(
      "Rates are placeholder concept rates for early estimation only. Actual cost depends on city, material quality, structural design, labor, finishing selection, soil condition, approvals, and contractor quotation.",
      180
    ),
    14,
    y + 63
  );

  addFooter(doc, page);

  const fileName = `${safeText(plan.title, "nexacad-project")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")}-proposal.pdf`;

  doc.save(fileName);
}